## Programming Assignment 8

In [1]:
import numpy as np 

1. Write a Python Program to Add Two Matrices?

In [4]:
def add_matrices(a,b):
    a = np.array(a)
    b = np.array(b) 
    try :
        return np.add(a,b)
    except Exception as e :
        return e 
array1 = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

array2 = [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]
print(add_matrices(array1,array2))
array1 = [[1, 2, 3],
          [4, 5, 6]]

array2 = [[7, 8],
          [9, 10],
          [11, 12]]
print(add_matrices(array1,array2))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
operands could not be broadcast together with shapes (2,3) (3,2) 


2. Write a Python Program to Multiply Two Matrices?

In [10]:
def mul_matrices(a,b):
    a = np.array(a)
    b = np.array(b) 
    try :
        return np.matmul(a,b)
    except Exception as e :
        return e 
array1 = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

array2 = [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]
print(mul_matrices(array1,array2))
array1 = [[1, 2, 3],
          [4, 5, 6]]
array2 = [[7, 8],
          [9, 10],
          [11, 12],
          [3,2]]
print(mul_matrices(array1,array2))

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)


3. Write a Python Program to Transpose a Matrix?

In [12]:
array1 = [[1, 2, 3],
          [4, 5, 6]]
array1 = np.transpose(np.array(array1))
array1 

array([[1, 4],
       [2, 5],
       [3, 6]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [13]:
words = ['apple', 'banana', 'cherry', 'date']

# Sort the words in alphabetical order
words.sort()

print(words)


['apple', 'banana', 'cherry', 'date']


5. Write a Python Program to Remove Punctuation From a String?

In [25]:
import string

# The string to be cleaned
s = '!@$#%^TFDGHehsgWRU$%%'

# Use a list comprehension to remove all punctuation from the string
cleaned = ''.join(c for c in s if c not in string.punctuation)

print(cleaned)




TFDGHehsgWRU
